#!/usr/bin/env python3
"""
Build graph_feature_catalogue.xlsx: documentation of all graph-based AML features
(generated by graph_feature_generator.ipynb), including meaning, formula, and value range.
"""
from pathlib import Path

def main():
    out_path = Path(__file__).resolve().parent.parent / "outputs" / "graph_feature_catalogue.xlsx"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    rows = [
        {
            "feature_name": "sender_in_degree_30d",
            "category": "Sender-side",
            "meaning": "Number of distinct incoming transactions (inflows) to the sender account in the rolling 30-day window ending at transaction time.",
            "formula_calculation": "Count of rows where account = sender and transaction is inflow, in window (t - 30d, t]. Inflow = internal transfers where this account is the receiver.",
            "value_range": "Non-negative integer (0, 1, 2, ...). Higher values indicate more incoming internal transfers.",
        },
        {
            "feature_name": "sender_out_degree_30d",
            "category": "Sender-side",
            "meaning": "Number of outgoing transactions (outflows) from the sender account in the rolling 30-day window ending at transaction time.",
            "formula_calculation": "Count of outflow transactions for the sender account in window (t - 30d, t].",
            "value_range": "Non-negative integer. Degree in the payment graph (out-edges).",
        },
        {
            "feature_name": "sender_total_inflow_30d",
            "category": "Sender-side",
            "meaning": "Total monetary amount received by the sender account (inflows) in the rolling 30-day window.",
            "formula_calculation": "Sum(amount) over inflow transactions for sender account in window (t - 30d, t].",
            "value_range": "Non-negative float (currency units). Can be 0 if no inflows in window.",
        },
        {
            "feature_name": "sender_total_outflow_30d",
            "category": "Sender-side",
            "meaning": "Total monetary amount sent by the sender account (outflows) in the rolling 30-day window.",
            "formula_calculation": "Sum(amount) over outflow transactions for sender account in window (t - 30d, t].",
            "value_range": "Non-negative float (currency units).",
        },
        {
            "feature_name": "sender_unique_counterparties_30d",
            "category": "Sender-side",
            "meaning": "Number of unique counterparties (receiver account or beneficiary) the sender transacted with in the last 30 days.",
            "formula_calculation": "Nunique(receiver_account_id or beneficiary_id) over outflow transactions in window (t - 30d, t].",
            "value_range": "Non-negative integer. 1 = single counterparty; higher = more dispersed.",
        },
        {
            "feature_name": "sender_repeat_counterparty_ratio",
            "category": "Sender-side",
            "meaning": "Proportion of outflow transactions that are to repeat counterparties (same counterparty multiple times) in the 30d window.",
            "formula_calculation": "1 - (sender_unique_counterparties_30d / sender_out_degree_30d). Replace 0/0 with 0.",
            "value_range": "0 to 1 (decimal). 0 = all unique counterparties; 1 = all to same counterparty.",
        },
        {
            "feature_name": "devices_per_account",
            "category": "Sender-side",
            "meaning": "Number of distinct devices used by the sender account for outflows in the rolling 30-day window.",
            "formula_calculation": "Nunique(device_id) over outflow transactions for sender in window (t - 30d, t].",
            "value_range": "Positive integer (1, 2, ...). Multiple devices can indicate shared or compromised accounts.",
        },
        {
            "feature_name": "receiver_in_degree_30d",
            "category": "Receiver-side",
            "meaning": "Number of incoming transactions (inflows) to the receiver account in the 30d window. Only for internal transfers (receiver_account_id present).",
            "formula_calculation": "Count of inflow rows where account = receiver, in window (t - 30d, t].",
            "value_range": "Non-negative integer. NaN or missing for beneficiary-only (external) transfers.",
        },
        {
            "feature_name": "receiver_out_degree_30d",
            "category": "Receiver-side",
            "meaning": "Number of outgoing transactions from the receiver account in the 30d window (same as sender_out_degree when receiver is the account).",
            "formula_calculation": "Same as sender_out_degree_30d but keyed by receiver_account_id; i.e. count of outflows where account = receiver in window.",
            "value_range": "Non-negative integer. Missing for external transfers.",
        },
        {
            "feature_name": "receiver_total_inflow_30d",
            "category": "Receiver-side",
            "meaning": "Total amount received by the receiver account in the 30d window (internal transfers only).",
            "formula_calculation": "Sum(amount) over inflows to receiver account in window (t - 30d, t].",
            "value_range": "Non-negative float. Missing for beneficiary-only rows.",
        },
        {
            "feature_name": "receiver_unique_senders_30d",
            "category": "Receiver-side",
            "meaning": "Number of unique sender accounts that sent money to this receiver in the 30d window.",
            "formula_calculation": "Nunique(sender_account_id) over inflow transactions where receiver = this account, in window (t - 30d, t].",
            "value_range": "Non-negative integer. High values can indicate aggregation/mule behavior.",
        },
        {
            "feature_name": "pass_through_ratio_24h",
            "category": "High-signal AML",
            "meaning": "Fraction of 24h inflow that is matched by outflow in the same 24h window (quick pass-through).",
            "formula_calculation": "min(sender_total_inflow_24h, sender_total_outflow_24h) / sender_total_inflow_24h. 0 if no inflow.",
            "value_range": "0 to 1. Near 1 = most inflow passed through in 24h (suspicious for layering/mules).",
        },
        {
            "feature_name": "pass_through_ratio_7d",
            "category": "High-signal AML",
            "meaning": "Fraction of 7-day inflow that is matched by outflow in the same 7d window.",
            "formula_calculation": "min(sender_total_inflow_7d, sender_total_outflow_7d) / sender_total_inflow_7d. 0 if no inflow.",
            "value_range": "0 to 1. High ratio suggests pass-through / layering behavior.",
        },
        {
            "feature_name": "outflow_to_inflow_ratio_7d",
            "category": "High-signal AML",
            "meaning": "Ratio of 7-day outflow to 7-day inflow for the sender account.",
            "formula_calculation": "sender_total_outflow_7d / sender_total_inflow_7d. 0 when inflow is 0.",
            "value_range": "Non-negative float. >1 = more outflow than inflow in 7d (may use prior balance or external funds).",
        },
        {
            "feature_name": "avg_time_gap_in_out",
            "category": "High-signal AML",
            "meaning": "Per account: average time (seconds) between an inflow and the next outflow. Low gap suggests quick pass-through.",
            "formula_calculation": "For each inflow timestamp, find the next outflow timestamp for same account; gap_sec = (t_out - t_in) in seconds; then average per account.",
            "value_range": "Non-negative float (seconds). Small values indicate fast turnover.",
        },
        {
            "feature_name": "accounts_per_device",
            "category": "Device / High-signal",
            "meaning": "Number of distinct sender accounts that used this device_id in the 30d window.",
            "formula_calculation": "Nunique(sender_account_id) over transactions with same device_id in window (t - 30d, t].",
            "value_range": "Positive integer. >1 suggests device sharing or multi-account abuse.",
        },
        {
            "feature_name": "device_shared_high_risk_ratio",
            "category": "Device / High-signal",
            "meaning": "Proportion of transactions on this device (30d window) that are fraud-labeled or involve high-risk beneficiaries.",
            "formula_calculation": "(sum(label) + sum(high_risk_beneficiary)) / count(transactions) for device in window. 0 when count is 0.",
            "value_range": "0 to 1. High values indicate device associated with fraud or high-risk activity.",
        },
        {
            "feature_name": "shared_device_fraud_count",
            "category": "Device / High-signal",
            "meaning": "Number of fraud-labeled transactions (label=1) on this device in the 30d rolling window.",
            "formula_calculation": "Sum(label) over transactions with same device_id in window (t - 30d, t].",
            "value_range": "Non-negative integer. >0 indicates device used in known fraud.",
        },
    ]

    try:
        import pandas as pd
        df = pd.DataFrame(rows)
        from openpyxl.utils import get_column_letter
        with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
            df.to_excel(writer, index=False, sheet_name="Graph features")
            ws = writer.sheets["Graph features"]
            for i, col in enumerate(df.columns, 1):
                max_len = max(df[col].astype(str).str.len().max(), len(col))
                ws.column_dimensions[get_column_letter(i)].width = min(max_len + 2, 100)
        print(f"Wrote {out_path}")
    except ImportError:
        import csv
        csv_path = out_path.with_suffix(".csv")
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=rows[0].keys())
            w.writeheader()
            w.writerows(rows)
        print(f"openpyxl not installed; wrote CSV: {csv_path}")
        print("Install with: pip install openpyxl")

if __name__ == "__main__":
    main()
